openapi: 3.0.0

info:
 version: '1.0'
 title: 'SoundSello Web API'
 description: 'Web Resources Specification (A7) for SoundSello'

servers:
- url: https://lbaw2322.lbaw.fe.up.pt
  description: Production server

externalDocs:
 description: More info here.
 url: https://git.fe.up.pt/lbaw/lbaw2324/lbaw2322/wiki/eap

tags:
 - name: 'M01: Authentication'
 - name: 'M02: Users'
 - name: 'M03: Auctions'
 - name: 'M04: Search'
 - name: 'M05: Administration'

paths:

############################################ AUTENTICATION ############################################

######### LOGIN #########

  /login:

    get:
      operationId: R101
      summary: 'R101: Login Form'
      description: 'Provide login form. Access: VIS'
      tags:
        - 'M01: Authentication'

      responses:
        '200':
          description: 'OK. Show log-in UI'

    post:
      operationId: R102
      summary: 'R102: Login Action'
      description: 'Processes the login form submission. Access: VIS'
      tags:
        - 'M01: Authentication'

      requestBody:
        required: true
        content:
          application/x-www-form-urllencoded:
            schema:
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
              required:
                  - email
                  - password

      responses:
        '302':
          description: 'Redirect after processing the new user information.'
          headers:
            Location:
              schema:
                type: string
              examples:
                302Success:
                  description: 'OK. You are in. Redirect to homepage.'
                  value: '/home'
                302Failure:
                  description: 'You shall not pass. Redirect again to login form.'
                  value: '/login'

######### LOGOUT #########

  /logout:

    get:
      operationId: R103
      summary: 'R103 : Logout Action'
      description: 'Logout the current logged user. Access: USR, SYS ,ADM'
      tags:
        - 'M01: Authentication'

      responses:
        '302':
          description: 'Redirect after processing logout.'
          headers:
            Location:
              schema:
                type: string
              examples:
                302Success:
                  description: 'Successful logout. Redirect to public feed.'
                  value: '/'

######### REGISTER #########

  /register:

    get:
      operationId: R104
      summary: 'R104 : Register Form'
      description: 'Register a new user. Access: VIS'
      tags:
        - 'M01: Authentication'

      responses:
        '200':
          description: 'Ok. Lets Sign-up.'

    post:
      operationId: R105
      summary: 'R105 : Register Action'
      description: 'Processes the new user registration form submission. Access: VIS'
      tags:
        - 'M01: Authentication'

      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
                confirm_password:
                  type: string
                  format: password
                date_of_birth:
                  type: string
                  format: date
                address:
                  type: string
                  format: address
              required:
                - username
                - email
                - password
                - confirm_password
                - date_of_birth;
## ask address----------------

      responses:
        '302':
          description: 'Redirect after processing the new user information.'
          headers:
            Location:
              schema:
                type: string
              example:
                  302Success:
                    description: 'Successful registration. Redirect to home page.'
                    value: '/home'
                  302Failure:
                    description: 'Failed registration. Redirect again to register form.'
                    value: '/register'


############################################ USERS ############################################

######### PROFILE #########

  /user/{id}:

    get:
      operationId: R201
      summary: 'R201: View user profile'
      description: 'Show the profile for an individual user, Access: CRE, ADM, SYS , VIS, CRE'
      tags:
        - 'M02: Users'

      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: True

      responses:
        '200':
          description: 'OK. Show the profile for an individual user'

######### VIEW USER AUCTIONS #########

/users/{id}/auctions:

      get: 
        operationId: R202
        summary: 'R202: View users auctions'
        description: 'Show auctions owned by a certain user, Access: CRE, SYS, ADM'
        tags:
          - 'M02: Users'

        parameters:
          -in: path
          name: id
          schema:
            type: integer
          required: True

        responses:
         '200':
           description: 'OK. Show list of auctions of an individual user'

######### VIEW USER FOLLOWED AUCTIONS #########

/users/{id}/followed_auctions:

      get: 
        operationId: R203
        summary: 'R203: View users follows auctions'
        description: 'Show auctions followed by a certain user, Access: CRE, SYS, ADM'
        tags:
          - 'M02: Users'

        parameters:
          -in: path
          name: id
          schema:
            type: integer
          required: True

        responses:
         '200':
          description: 'OK. Show list of auctions followed by a user'


############################################ AUCTIONS ############################################

######### CREATE AUCTION #########

/auction/create:

    post:
      operationId: R301
      summary: 'R301: Create auction action'
      description: 'Auction post. Access: USR, SYS, ADM'
      tags:
        - 'M03: Auctions'

      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                title:
                  type: string
                media:
                  type: string
                  format: binary
                description:
                  type: string
                initial_price: 
                  type: integer
                initial_date:
                  type: string
                  format: date
                end_date:
                  type: string
                  format: date
                
      responses:
        '201':
          description: 'Auction created successfully.'
          headers:
            Location: 
              schema:
                type: string


######### VIEW AUCTION DETAILS #########

/auctions/{id}:
  get:
    operationId: R302
    summary: 'R302: Retrieve details of an auction'
    description: 'Retrieve details of a specific auction. Access: VIS, USR, CRE, SYS, ADM'
    tags:
      - 'M03: Auctions'
    parameters:
      - name: id
        in: path
        required: true
        description: 'Unique identifier of the auction.'
        schema:
          type: string
    responses:
      '200':
        description: 'Auction details retrieved successfully.'
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                initial_price:
                  type: number
                current_price:
                  type: number
                initial_date:
                  type: string
                end_date:
                  type: string
                owner:
                  type: object
                  properties:
                    id:
                      type: string
                    username:
                      type: string
              ## ver categorias e estados
      '404':
        description: 'Not found. Auction does not exist.'

  put:
    operationId: R503
    summary: 'R503: Change the state of an auction'
    description: 'Change the state of a specific auction. Access: CRE, SYS, ADM'
    tags:
      - 'Auctions'
    parameters:
      - name: id
        in: path
        required: true
        description: 'Unique identifier of the auction.'
        schema:
          type: string
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              auction_state:
                type: string
    responses:
      '200':
        description: 'Auction state changed successfully.'
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                new_state:
                  type: string
      '400':
        description: 'Bad request. Invalid status change data.'
      '401':
        description: 'Unauthorized. User not authenticated.'
      '403':
        description: 'Forbidden. User does not have permission to change the status.'
      '404':
        description: 'Not found. Auction does not exist.'


##### FOLLOW AUCTION #####

  /auctions/{id}/follow:

    post:
      operationId: R303
      summary: 'R303: Follows Auction.'
      description: 'Follows auction. Access: USR, SYS, ADM'
      tags:
        - 'M03: Auctions'

      requestBody:
          required: true
          content:
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                required:
                  - id

      responses:
        '200':
          description: 'Ok. You followed a user.'
        '403':
          description: 'Forbiden action.'

######### UNFOLLOW AUCTION #########

  /auctions/{id}/unfollow:

    post:
      operationId: R304
      summary: 'R304: Unfollows auction.'
      description: 'Unfollows auction. Access: USR, SYS , ADM'
      tags:
        - 'M03: Auctions'

      requestBody:
          required: true
          content:
            application/x-www-form-urlencoded:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                required:
                  - id

      responses:
        '200':
          description: 'Ok. You unfollowed an auction.'
        '403':
          description: 'Forbiden action.'


######### BID IN AUCTION #########

  /auctions/{id}/bid:

    post:
      operationId: R305
      summary: 'R305: Place Bid'
      description: 'Place Bid. Access: USR, SYS, ADM'
      tags:
        - 'M03: Auctions'

      parameters:
        - name: auction_id
          in: path
          required: true
          description: 'Unique identifier of the auction.'
          schema:
            type: string

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                bid_amount:
                  type: number
      responses:
        '200':
          description: 'New Bid.'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  new_highest_bid:
                    type: number

######### COMMENT IN AUCTION #########

/auctions/{id}/comment:

    post:
      operationId: R306
      summary: 'R306: Add a comment to an auction'
      description: 'Add a comment to a specific auction. Access: USR, CRE , SYS, ADM'
      tags:
        - 'M03: Auctions'

      parameters:
        - name: id
          in: path
          required: true
          description: 'Unique identifier of the auction.'
          schema:
            type: string

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                user_id:
                  type: string
                timestamp:
                  type: string

      responses:
        '201':
          description: 'Comment added successfully.'
          content:
            application/json:
              schema:
                type: object
                properties:
                  comment:
                    type: string
                  id:
                    type: string
                  date:
                    type: string
        '400':
          description: 'Bad request. Invalid comment data.'
        '401':
          description: 'Unauthorized. User not authenticated.'
        '403':
          description: 'Forbidden. User does not have permission to add comments.'

############################################ SEARCH ############################################

/api/user:

    get:
      operationId: R401
      summary: 'R401 : Search users'
      description: 'Search users. Access: VIS, USR, SYS,ADM'
      tags:
        - 'M04: Search'

      parameters:
        - in: query
          name: search
          description: 'Search content'
          schema:
            type: string
          required: true

      responses:
        '200':
          description: 'Success. Returns a list of users information.'


####### SEARCH AUCTION ######

/api/auctions:

    get:
      operationId: R402
      summary: 'R402: Search for auctions'
      description: 'Search for auctions based on specific criteria. Access: AUTH'
      tags:
        - 'Auctions'

      parameters:
        - in: query
          name: search
          description: 'Search content'
          schema:
            type: string
          required: true

      responses:
        '200':
          description: 'Success. Returns a list of auctions information'

############################################ ADMINISTRATION ############################################

######### ADMIN PAGE #########

/admin:

    get:
      operationId: R501
      summary: 'R501: View admin page'
      description: 'Show admin page UI, Access: ADM'
      tags:
        - 'M05: Administration'

      responses:
        '200':
          description: 'OK. Show the admin page UI'
        '403':
          description: 'This action is unauthorized.'

/admin/users:

    get: 
      operationId: R502
      summary: '502: View all users'
      description: 'View all users'
      tags:
        - 'M05'

      responses:
          '200':
            description: 'OK. Show all users page UI'
          '403':
            description: 'This action is unauthorized.'
