openapi: 3.0.0

info:
  version: '1.0'
  title: 'SoundSello Web API'
  description: 'Web Resources Specification (A7) for SoundSello'

servers:
  - url: https://lbaw2322.lbaw.fe.up.pt
    description: Production server

externalDocs:
  description: More info here.
  url: https://git.fe.up.pt/lbaw/lbaw2324/lbaw2322/wiki/eap

tags:
  - name: 'M01: Authentication'
  - name: 'M02: Users'
  - name: 'M03: Auctions'
  - name: 'M04: Search'
  - name: 'M05: Administration'

paths:

  /login:
    get:
      operationId: R101
      summary: 'R101: Login Form'
      description: 'Provide login form. Access: VIS'
      tags:
        - 'M01: Authentication'
      responses:
        '200':
          description: 'OK. Show log-in UI'

    post:
      operationId: R102
      summary: 'R102: Login Action'
      description: 'Processes the login form submission. Access: VIS'
      tags:
        - 'M01: Authentication'
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
              required:
                - email
                - password
      responses:
        '302':
          description: 'Redirect after processing the new user information.'
          headers:
            Location:
              schema:
                type: string
              examples:
                302Success:
                  description: 'OK. You are in. Redirect to homepage.'
                  value: '/home'
                302Failure:
                  description: 'You shall not pass. Redirect again to login form.'
                  value: '/login'

  /logout:
    get:
      operationId: R103
      summary: 'R103: Logout Action'
      description: 'Logout the current logged user. Access: USR, SYS, ADM'
      tags:
        - 'M01: Authentication'
      responses:
        '302':
          description: 'Redirect after processing logout.'
          headers:
            Location:
              schema:
                type: string
              examples:
                302Success:
                  description: 'Successful logout. Redirect to public feed.'
                  value: '/'

  /register:
    get:
      operationId: R104
      summary: 'R104: Register Form'
      description: 'Register a new user. Access: VIS'
      tags:
        - 'M01: Authentication'
      responses:
        '200':
          description: 'Ok. Lets Sign-up.'

    post:
      operationId: R105
      summary: 'R105: Register Action'
      description: 'Processes the new user registration form submission. Access: VIS'
      tags:
        - 'M01: Authentication'
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                username:
                  type: string
                name:
                  type: string
                email:
                  type: string
                  format: email
                password:
                  type: string
                  format: password
                confirm_password:
                  type: string
                  format: password
                date_of_birth:
                  type: string
                  format: date
              required:
                - username
                - name
                - email
                - password
                - confirm_password
                - date_of_birth
      responses:
        '302':
          description: 'Redirect after processing the new user information.'
          headers:
            Location:
              schema:
                type: string
              example:
                302Success:
                  description: 'Successful registration. Redirect to home page.'
                  value: '/home'
                302Failure:
                  description: 'Failed registration. Redirect again to register form.'
                  value: '/register'

